# Generated by Django 2.1.7 on 2019-03-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Enter the name of a free to access book', max_length=1000),
        ),
    ]
