# Generated by Django 2.1.7 on 2019-03-11 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190311_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='programming_language',
            field=models.TextField(default=django.utils.timezone.now, help_text='Enter the programming language that the book discusses.', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(help_text='Enter a description of the book.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Enter the name of a free to access programming book.', max_length=200),
        ),
    ]
