# Generated by Django 2.1.7 on 2019-03-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190311_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='programming_language',
        ),
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='N/A', help_text='Enter a description of the book.', max_length=1000),
        ),
        migrations.AddField(
            model_name='book',
            name='programming_Language',
            field=models.CharField(default='N/A', help_text='Enter the programming language that the book discusses.', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='N/A', help_text='Enter the name of the author.', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='N/A', help_text='Enter the name of a free to access programming book.', max_length=200),
        ),
    ]
