# Generated by Django 2.1.7 on 2019-03-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190311_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.TextField(default='N/A', help_text='Enter the URL slug.', max_length=1000),
        ),
        migrations.AddField(
            model_name='book',
            name='uRL',
            field=models.TextField(default='N/A', help_text='Enter the URL of the book.', max_length=1000),
        ),
    ]
