# Generated by Django 2.1.7 on 2019-03-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='N/A', help_text='Enter the URL slug.', max_length=1000),
        ),
    ]
