# Generated by Django 2.1.7 on 2019-03-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_awk'),
    ]

    operations = [
        migrations.CreateModel(
            name='bash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='N/A', help_text='Enter the name of a free to access programming book.', max_length=200)),
                ('author', models.CharField(default='N/A', help_text='Enter the name of the author.', max_length=200)),
                ('category_or_Programming_Language', models.CharField(default='N/A', help_text='Enter the category/programming language of the book.', max_length=200)),
                ('description', models.TextField(default='N/A', help_text='Enter a description of the book.', max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('uRL', models.TextField(default='N/A', help_text='Enter the URL of the book.', max_length=1000)),
                ('slug', models.TextField(default='N/A', help_text='Enter the URL slug.', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='html',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='N/A', help_text='Enter the name of a free to access programming book.', max_length=200)),
                ('author', models.CharField(default='N/A', help_text='Enter the name of the author.', max_length=200)),
                ('category_or_Programming_Language', models.CharField(default='N/A', help_text='Enter the category/programming language of the book.', max_length=200)),
                ('description', models.TextField(default='N/A', help_text='Enter a description of the book.', max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('uRL', models.TextField(default='N/A', help_text='Enter the URL of the book.', max_length=1000)),
                ('slug', models.TextField(default='N/A', help_text='Enter the URL slug.', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='javascript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='N/A', help_text='Enter the name of a free to access programming book.', max_length=200)),
                ('author', models.CharField(default='N/A', help_text='Enter the name of the author.', max_length=200)),
                ('category_or_Programming_Language', models.CharField(default='N/A', help_text='Enter the category/programming language of the book.', max_length=200)),
                ('description', models.TextField(default='N/A', help_text='Enter a description of the book.', max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('uRL', models.TextField(default='N/A', help_text='Enter the URL of the book.', max_length=1000)),
                ('slug', models.TextField(default='N/A', help_text='Enter the URL slug.', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ruby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='N/A', help_text='Enter the name of a free to access programming book.', max_length=200)),
                ('author', models.CharField(default='N/A', help_text='Enter the name of the author.', max_length=200)),
                ('category_or_Programming_Language', models.CharField(default='N/A', help_text='Enter the category/programming language of the book.', max_length=200)),
                ('description', models.TextField(default='N/A', help_text='Enter a description of the book.', max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('uRL', models.TextField(default='N/A', help_text='Enter the URL of the book.', max_length=1000)),
                ('slug', models.TextField(default='N/A', help_text='Enter the URL slug.', max_length=1000)),
            ],
        ),
    ]
